// src/pages/Center/Database.vue
<template>
  <!--#region 研究中心库管理页面 -->
  <t-card bordered style="height: calc(100vh - 80px)">
    <!-- 页面标题 -->
    <div style="margin-bottom: 16px">
      <h2 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 600; color: var(--td-text-color-primary)">
        研究中心库
      </h2>

      <!--#region 搜索表单 -->
      <div
        style="
          background: #f8fafc;
          padding: 16px;
          border-radius: 12px;
          border: 1px solid var(--td-border-level-1-color);
        "
      >
        <t-form
          ref="formRef"
          :data="formData"
          layout="inline"
          label-width="120"
          style="display: flex; gap: 16px 0; flex-wrap: wrap"
          @submit="onSearch"
        >
          <t-form-item label="中心名称（标准名）" name="hosStandardName" style="margin-bottom: 0">
            <t-input v-model="formData.hosStandardName" placeholder="请输入" clearable style="width: 220px" />
          </t-form-item>
          <div style="display: flex; align-items: center; margin-left: auto">
            <t-space>
              <t-button theme="primary" type="submit"> 搜索 </t-button>
            </t-space>
          </div>
        </t-form>
      </div>
      <!--#endregion-->
    </div>

    <!--#region 数据表格 -->
    <t-table
      :data="tableData"
      :columns="columns"
      row-key="id"
      :loading="loading"
      bordered
      stripe
      table-layout="fixed"
      max-height="calc(100vh - 280px)"
      style="white-space: nowrap"
      :pagination="pagination"
      @page-change="onPageChange"
    >
      <template #operation="{ row }">
        <t-button theme="primary" @click="openEditModal(row)"> 编辑 </t-button>
      </template>
    </t-table>
    <!--#endregion-->

    <!--#region 源数据研究中心名(别名)弹窗 -->
    <t-dialog
      v-model:visible="sourceModalVisible"
      header="源数据研究中心名(别名)"
      :footer="false"
      width="600px"
      @close="onSourceModalClose"
    >
      <t-table
        :data="sourceData"
        :columns="sourceColumns"
        row-key="originName"
        :loading="sourceLoading"
        bordered
        stripe
        :pagination="sourcePagination"
        @page-change="onSourcePageChange"
      />
    </t-dialog>
    <!--#endregion-->

    <!--#region 编辑/新增弹窗 -->
    <t-dialog
      v-model:visible="editModalVisible"
      :header="currentEditRecord ? '编辑' : '新增'"
      width="500px"
      :confirm-btn="{ content: '保存', theme: 'primary', loading: editLoading }"
      @confirm="submitEdit"
      @close="onEditModalClose"
    >
      <t-form ref="editFormRef" :data="editFormData" label-width="120" label-align="left">
        <t-form-item label="标准名称" name="hosStandardName">
          <t-input v-model="editFormData.hosStandardName" />
        </t-form-item>
        <t-form-item label="简称" name="hosShortName">
          <t-input v-model="editFormData.hosShortName" />
        </t-form-item>
        <t-form-item label="省份" name="province">
          <t-input v-model="editFormData.province" />
        </t-form-item>
        <t-form-item label="城市" name="city">
          <t-input v-model="editFormData.city" />
        </t-form-item>
        <t-form-item label="备注" name="remark">
          <t-textarea v-model="editFormData.remark" />
        </t-form-item>
      </t-form>
    </t-dialog>
    <!--#endregion-->
  </t-card>
  <!--#endregion-->
</template>

<script setup lang="ts">
//#region Imports
import { ref, reactive, h, onMounted } from 'vue';
import { MessagePlugin } from 'tdesign-vue-next';
import moment from 'moment';
import { hospitalApi } from '@/api';
import type { StandardHospitalDto } from '@/api/types/hospital';
//#endregion

//#region State
const formRef = ref();
const editFormRef = ref();
const loading = ref(false);
const tableData = ref<StandardHospitalDto[]>([]);
const pagination = reactive({
  current: 1,
  pageSize: 20,
  total: 0,
  showJumper: true,
  foldedMaxPageBtn: 3,
});

const formData = reactive<Record<string, any>>({
  hosStandardName: '',
});

// 源数据弹窗
const sourceModalVisible = ref(false);
const sourceData = ref<{ originName: string }[]>([]);
const sourceLoading = ref(false);
const sourcePagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
});
const currentHospitalId = ref<number>();

// 编辑弹窗
const editModalVisible = ref(false);
const editLoading = ref(false);
const currentEditRecord = ref<StandardHospitalDto | null>(null);

const editFormData = reactive<Record<string, any>>({
  hosStandardName: '',
  hosShortName: '',
  province: '',
  city: '',
  remark: '',
});
//#endregion

//#region Columns Definition
const columns = [
  {
    colKey: 'rowIndex',
    title: '序号',
    width: 80,
    cell: (h: any, { rowIndex }: any) => rowIndex + 1 + (pagination.current - 1) * pagination.pageSize,
  },
  { colKey: 'hosStandardName', title: '中心名称（标准名）', width: 300, ellipsis: true },
  { colKey: 'province', title: '省份', width: 150 },
  { colKey: 'city', title: '城市', width: 150 },
  {
    colKey: 'cnt',
    title: '别名',
    width: 80,
    align: 'center' as const,
    cell: (h: any, { row }: any) =>
      h(
        'span',
        {
          style: { color: '#0052d9', cursor: 'pointer' },
          onClick: () => openSourceModal(row.id!),
        },
        row.cnt || 0,
      ),
  },
  { colKey: 'hosShortName', title: '简称', width: 200, ellipsis: true },
  { colKey: 'updater', title: '操作人', width: 100 },
  {
    colKey: 'updateTime',
    title: '更新时间',
    width: 170,
    cell: (h: any, { row }: any) => (row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-'),
  },
  {
    colKey: 'operation',
    title: '操作',
    width: 100,
    fixed: 'right' as const,
  },
];

const sourceColumns = [
  {
    colKey: 'rowIndex',
    title: '序号',
    width: 80,
    cell: (h: any, { rowIndex }: any) => rowIndex + 1 + (sourcePagination.current - 1) * sourcePagination.pageSize,
  },
  { colKey: 'originName', title: '研究中心别名(源数名称)' },
];
//#endregion

//#region Data Fetching
const fetchData = async (curr = pagination.current, size = pagination.pageSize) => {
  loading.value = true;
  try {
    const params: Record<string, any> = {
      ...formData,
      pageNum: curr,
      pageSize: size,
    };
    const res = await hospitalApi.queryStandardList(params);
    tableData.value = res.data?.list || [];
    pagination.current = curr;
    pagination.pageSize = size;
    pagination.total = res.data?.total || 0;
  } catch (e) {
    console.error(e);
  } finally {
    loading.value = false;
  }
};

const onSearch = () => fetchData(1);
const onPageChange = (pageInfo: any) => {
  fetchData(pageInfo.current, pageInfo.pageSize);
};
//#endregion

//#region Source Modal
const fetchSourceData = async (hospitalId: number, curr = 1, size = 10) => {
  sourceLoading.value = true;
  try {
    const res = await hospitalApi.queryOriginHospitalList({ queryId: hospitalId, pageNum: curr, pageSize: size });
    const mappedList = (res.data?.list || []).map((name: string) => ({ originName: name }));
    sourceData.value = mappedList;
    sourcePagination.current = curr;
    sourcePagination.pageSize = size;
    sourcePagination.total = res.data?.total || 0;
  } catch (e) {
    console.error(e);
  } finally {
    sourceLoading.value = false;
  }
};

const openSourceModal = (id: number) => {
  currentHospitalId.value = id;
  fetchSourceData(id, 1, 10);
  sourceModalVisible.value = true;
};

const onSourcePageChange = (pageInfo: any) => {
  if (currentHospitalId.value) {
    fetchSourceData(currentHospitalId.value, pageInfo.current, pageInfo.pageSize);
  }
};

const onSourceModalClose = () => {
  sourceModalVisible.value = false;
};
//#endregion

//#region Edit Modal
const openEditModal = (record?: StandardHospitalDto) => {
  if (record) {
    currentEditRecord.value = record;
    editFormData.hosStandardName = record.hosStandardName || '';
    editFormData.hosShortName = record.hosShortName || '';
    editFormData.province = record.province || '';
    editFormData.city = record.city || '';
    editFormData.remark = record.remark || '';
    editModalVisible.value = true;
  } else {
    currentEditRecord.value = null;
    editFormData.hosStandardName = '';
    editFormData.hosShortName = '';
    editFormData.province = '';
    editFormData.city = '';
    editFormData.remark = '';
    editModalVisible.value = true;
  }
};

const submitEdit = async () => {
  editLoading.value = true;
  try {
    const submitData: StandardHospitalDto = {
      ...currentEditRecord.value,
      hosStandardName: editFormData.hosStandardName,
      hosShortName: editFormData.hosShortName,
      province: editFormData.province,
      city: editFormData.city,
      remark: editFormData.remark,
    };
    await hospitalApi.saveStandardHospital(submitData);
    MessagePlugin.success('保存成功');
    editModalVisible.value = false;
    fetchData();
  } catch (e) {
    console.error(e);
  } finally {
    editLoading.value = false;
  }
};

const onEditModalClose = () => {
  editModalVisible.value = false;
  currentEditRecord.value = null;
};
//#endregion

//#region Lifecycle
onMounted(() => {
  fetchData();
});
//#endregion
</script>

// src/pages/Company/Database.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Space, Input, Select, Form, Dialog, MessagePlugin, Card, Textarea } from 'tdesign-react';
import moment from 'moment';
import { companyApi } from '../../api';
import type { StandardCompanyDto, CompanyQueryParam } from '../../api';

const companyTypeOptions = [
  { label: '药企', value: '药企' },
  { label: 'CRO', value: 'CRO' },
  { label: '申办方', value: '申办方' },
  { label: '第三方实验室', value: '第三方实验室' },
  { label: '其他', value: '其他' },
];

const CompanyDatabase: React.FC = () => {
  const [form] = Form.useForm();
  const isFirstRender = useRef(true);

  // ----- Table State -----
  const [data, setData] = useState<StandardCompanyDto[]>([]);
  const [loading, setLoading] = useState(false);
  const [pagination, setPagination] = useState({ current: 1, pageSize: 20, total: 0 });

  const fetchData = async (curr = pagination.current, size = pagination.pageSize) => {
    setLoading(true);
    try {
      const values = form.getFieldsValue(true);
      const params: CompanyQueryParam = {
        ...values,
        pageNum: curr,
        pageSize: size,
      };

      const res = await companyApi.queryStandardList(params);
      setData(res.data?.list || []);
      setPagination({ current: curr, pageSize: size, total: res.data?.total || 0 });
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      fetchData();
    }
  }, []);

  const onSearch = () => fetchData(1);

  // ----- 别名(源数据) Modal -----
  const [sourceModalVisible, setSourceModalVisible] = useState(false);
  const [sourceData, setSourceData] = useState<{ originName: string }[]>([]);
  const [sourceLoading, setSourceLoading] = useState(false);
  const [sourcePagination, setSourcePagination] = useState({ current: 1, pageSize: 10, total: 0 });
  const [currentCompanyId, setCurrentCompanyId] = useState<number>();

  const fetchSourceData = async (companyId: number, curr = 1, size = 10) => {
    setSourceLoading(true);
    try {
      const res = await companyApi.getOriginCompanies({ queryId: companyId, pageNum: curr, pageSize: size });
      const mappedList = (res.data?.list || []).map((name) => ({ originName: name }));
      setSourceData(mappedList);
      setSourcePagination({ current: curr, pageSize: size, total: res.data?.total || 0 });
    } catch (e) {
      console.error(e);
    } finally {
      setSourceLoading(false);
    }
  };

  const openSourceModal = (id: number) => {
    setCurrentCompanyId(id);
    fetchSourceData(id, 1, 10);
    setSourceModalVisible(true);
  };

  // ----- 编辑 Modal -----
  const [editModalVisible, setEditModalVisible] = useState(false);
  const [editForm] = Form.useForm();
  const [editLoading, setEditLoading] = useState(false);
  const [currentEditRecord, setCurrentEditRecord] = useState<StandardCompanyDto | null>(null);

  // 监听编辑状态和数据，处理表单回显
  useEffect(() => {
    if (editModalVisible) {
      if (currentEditRecord) {
        // 编辑模式：填充数据，使用 setTimeout 确保表单项已注册
        const timer = setTimeout(() => {
          editForm.setFieldsValue({
            companyStandardName: currentEditRecord.companyStandardName,
            companyShortName: currentEditRecord.companyShortName,
            companyType: currentEditRecord.companyType,
            parentCompanyShortName: currentEditRecord.parentCompanyShortName,
            remark: currentEditRecord.remark,
          });
        }, 0);
        return () => clearTimeout(timer);
      } else {
        // 新增模式：重置表单
        editForm.reset();
      }
    }
    return undefined;
  }, [editModalVisible, currentEditRecord, editForm]);

  const openEditModal = async (record?: StandardCompanyDto) => {
    if (record && record.id) {
      // Edit mode
      setCurrentEditRecord(record);
      setEditModalVisible(true);
      setEditLoading(true);
      try {
        const res = await companyApi.getStandardCompany(record.id);
        setCurrentEditRecord(res.data);
      } catch (e) {
        console.error(e);
        setEditModalVisible(false);
      } finally {
        setEditLoading(false);
      }
    } else {
      // Create mode
      setCurrentEditRecord(null);
      setEditModalVisible(true);
    }
  };

  const submitEdit = async () => {
    try {
      const values = await editForm.validate();
      if (values === true) {
        setEditLoading(true);
        const fields = editForm.getFieldsValue(true);
        const submitData: StandardCompanyDto = {
          ...currentEditRecord,
          companyStandardName: fields.companyStandardName,
          companyShortName: fields.companyShortName,
          companyType: fields.companyType,
          parentCompanyShortName: fields.parentCompanyShortName, // Mapping to API property
          remark: fields.remark,
        };
        await companyApi.saveStandardCompany(submitData);
        MessagePlugin.success('保存成功');
        setEditModalVisible(false);
        fetchData();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setEditLoading(false);
    }
  };

  // ----- Table Columns -----
  const columns = [
    {
      colKey: 'rowIndex',
      title: '序号',
      width: 80,
      cell: ({ rowIndex }: any) => rowIndex + 1 + (pagination.current - 1) * pagination.pageSize,
    },
    { colKey: 'companyStandardName', title: '公司名(标准名称)', width: 280 },
    {
      colKey: 'cnt',
      title: '相关备案/登记号',
      width: 80,
      align: 'center' as const,
      cell: ({ row }: any) => (
        <div
          style={{
            padding: '4px',
            color: '#0052d9',
            cursor: 'pointer',
            display: 'inline-block',
            minWidth: '40px',
          }}
          onClick={() => openSourceModal(row.id!)}
        >
          {row.cnt || 0}
        </div>
      ),
    },
    { colKey: 'companyType', title: '公司类型', width: 100 },
    { colKey: 'companyShortName', title: '公司简称', width: 180, ellipsis: true },
    { colKey: 'parentCompanyShortName', title: '母公司简称', width: 180, ellipsis: true }, // API has parentCompanyShortName

    { colKey: 'updater', title: '操作人', width: 100 },
    {
      colKey: 'updateTime',
      title: '更新时间',
      width: 170,
      cell: ({ row }: any) => (row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-'),
    },
    {
      colKey: 'operation',
      title: '编辑修正',
      width: 100,
      fixed: 'right' as const,
      cell: ({ row }: any) => (
        <div style={{ padding: '2px 8px', display: 'inline-block' }}>
          <Button theme="primary" variant="text" onClick={() => openEditModal(row)}>
            编辑
          </Button>
        </div>
      ),
    },
  ];

  const sourceColumns = [
    {
      colKey: 'rowIndex',
      title: '序号',
      width: 80,
      cell: ({ rowIndex }: any) => rowIndex + 1 + (sourcePagination.current - 1) * sourcePagination.pageSize,
    },
    { colKey: 'originName', title: '公司别名(源数名称)' },
  ];

  return (
    <Card bordered={false} style={{ height: 'calc(100vh - 86px)' }}>
      <div style={{ marginBottom: 10 }}>
        <h2 style={{ margin: '0 0 16px 0', fontSize: '18px', fontWeight: 600, color: 'var(--td-text-color-primary)' }}>
          公司名库
        </h2>
        <div
          style={{
            background: '#f8fafc',
            padding: '10px',
            borderRadius: '12px',
            border: '1px solid var(--td-border-level-1-color)',
          }}
        >
          <Form
            form={form}
            layout="inline"
            labelWidth={120}
            style={{ display: 'flex', gap: '16px 0', flexWrap: 'wrap' }}
          >
            <Form.FormItem label="公司名(标准名)" name="companyName" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入" clearable style={{ width: 220 }} />
            </Form.FormItem>
            <Form.FormItem label="母公司简称" name="parentCompanyShortName" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入" clearable style={{ width: 220 }} />
            </Form.FormItem>
            <Form.FormItem label="公司类型" name="companyType" style={{ marginBottom: 0 }}>
              <Select options={companyTypeOptions} placeholder="请选择" clearable style={{ width: 220 }} />
            </Form.FormItem>
            <div style={{ display: 'flex', alignItems: 'center', marginLeft: 'auto' }}>
              <Space>
                <Button theme="primary" onClick={onSearch}>
                  搜索
                </Button>
              </Space>
            </div>
          </Form>
        </div>
      </div>

      <Table
        data={data}
        columns={columns}
        rowKey="id"
        loading={loading}
        pagination={{
          current: pagination.current,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showJumper: true,
          onChange: (pageInfo) => fetchData(pageInfo.current, pageInfo.pageSize),
        }}
        bordered
        stripe
        tableLayout="fixed"
        maxHeight="calc(100vh - 300px)"
        style={{ whiteSpace: 'nowrap' }}
      />

      {/* 别名源数据弹窗 */}
      <Dialog
        header="源数据公司名(别名)"
        visible={sourceModalVisible}
        onClose={() => setSourceModalVisible(false)}
        footer={null}
        width={600}
      >
        <Table
          data={sourceData}
          columns={sourceColumns}
          rowKey="originName"
          loading={sourceLoading}
          pagination={{
            current: sourcePagination.current,
            pageSize: sourcePagination.pageSize,
            total: sourcePagination.total,
            onChange: (pageInfo) => fetchSourceData(currentCompanyId!, pageInfo.current, pageInfo.pageSize),
          }}
          bordered
          stripe
        />
      </Dialog>

      {/* 编辑弹窗 */}
      <Dialog
        header={currentEditRecord ? '编辑' : '新增'}
        visible={editModalVisible}
        onClose={() => {
          setEditModalVisible(false);
          setCurrentEditRecord(null);
        }}
        onConfirm={submitEdit}
        confirmBtn={{ content: '保存', theme: 'primary', loading: editLoading }}
        width={500}
      >
        <Form form={editForm} labelWidth={140} labelAlign="left">
          <Form.FormItem label="公司名(标准名称)" name="companyStandardName">
            <Input />
          </Form.FormItem>
          <Form.FormItem label="公司简称" name="companyShortName">
            <Input />
          </Form.FormItem>
          <Form.FormItem label="公司类型" name="companyType">
            <Select options={companyTypeOptions} placeholder="请选择" />
          </Form.FormItem>
          <Form.FormItem label="母公司简称" name="parentCompanyShortName">
            <Input />
          </Form.FormItem>
          <Form.FormItem label="备注" name="remark">
            <Textarea />
          </Form.FormItem>
        </Form>
      </Dialog>
    </Card>
  );
};

export default CompanyDatabase;
