// src/pages/Drug/Clean.vue
<template>
  <!--#region 药品名清洗页面 -->
  <t-card bordered>
    <div style="margin-bottom: 16px">
      <h2 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 600; color: var(--td-text-color-primary)">
        药品名清洗
      </h2>

      <!--#region 搜索表单 -->
      <div
        style="
          background: #f8fafc;
          padding: 16px;
          border-radius: 12px;
          border: 1px solid var(--td-border-level-1-color);
        "
      >
        <t-form
          ref="formRef"
          :data="formData"
          layout="inline"
          label-width="140"
          style="display: flex; gap: 16px 0; flex-wrap: wrap"
          @submit="onSearch"
        >
          <t-form-item label="药品名（清洗后）" name="drugStandardName" style="margin-bottom: 0">
            <t-input v-model="formData.drugStandardName" placeholder="请输入关键字" clearable style="width: 220px" />
          </t-form-item>
          <t-form-item label="清洗状态" name="status" style="margin-bottom: 0">
            <t-select
              v-model="formData.status"
              :options="statusOptions"
              placeholder="请选择状态"
              clearable
              style="width: 220px"
            />
          </t-form-item>
          <div style="display: flex; align-items: center; margin-left: auto">
            <t-button theme="default" @click="onReset" style="background: #fff; margin-right: 8px"> 重置条件 </t-button>
            <t-button theme="primary" type="submit"> 立即查询 </t-button>
          </div>
        </t-form>
      </div>
      <!--#endregion-->
    </div>

    <!--#region 数据表格 -->
    <t-table
      :data="tableData"
      :columns="columns"
      row-key="drugCommentId"
      :loading="loading"
      bordered
      stripe
      table-layout="auto"
      hover
      :pagination="pagination"
      @page-change="onPageChange"
    />
    <!--#endregion-->

    <!--#region 相关备案/登记号弹窗 -->
    <t-dialog
      v-model:visible="accModalVisible"
      header="相关备案/登记号"
      :footer="false"
      width="800px"
      @close="onAccModalClose"
    >
      <t-table :data="accData" :columns="accColumns" row-key="id" bordered :pagination="accPagination" />
    </t-dialog>
    <!--#endregion-->

    <!--#region 编辑弹窗 -->
    <t-dialog
      v-model:visible="editModalVisible"
      header="编辑"
      width="600px"
      :confirm-btn="{ content: '提交', theme: 'primary', loading: editLoading }"
      @confirm="submitEdit"
      @close="onEditModalClose"
    >
      <div style="background-color: #f3f4f6; padding: 16px; margin-bottom: 16px; border-radius: 4px">
        <p style="margin: 0 0 8px 0">
          <strong>药品名（源数据）：</strong>
          {{ currentEditRecord?.drugNickName || currentEditRecord?.drugComment || currentEditRecord?.drugStandardName }}
        </p>
        <p style="margin: 0">
          <strong>药品类型：</strong>
          {{ currentEditRecord?.drugType || '化学药物' }}
        </p>
      </div>
      <t-form ref="editFormRef" :data="editFormData" label-width="180" label-align="left">
        <t-form-item label="药品名（清洗后）" name="cleanedName">
          <t-input v-model="editFormData.cleanedName" />
        </t-form-item>
        <t-form-item label="通用名（中文）" name="genericNameCn">
          <t-input v-model="editFormData.genericNameCn" />
        </t-form-item>
        <t-form-item label="通用名（英文）" name="genericNameEn">
          <t-input v-model="editFormData.genericNameEn" />
        </t-form-item>
        <t-form-item label="研发代号" name="rdCode">
          <t-input v-model="editFormData.rdCode" />
        </t-form-item>
        <t-form-item label="其他名（例如结构名称）" name="otherNames">
          <t-input v-model="editFormData.otherNames" />
        </t-form-item>
        <t-form-item label="剂型" name="dosageForm">
          <t-select v-model="editFormData.dosageForm" :options="dosageFormOptions" placeholder="请选择" />
        </t-form-item>
        <t-form-item label="药品类型" name="drugType">
          <t-select v-model="editFormData.drugType" :options="drugTypeOptions" placeholder="请选择" />
        </t-form-item>
      </t-form>
    </t-dialog>
    <!--#endregion-->
  </t-card>
  <!--#endregion-->
</template>

<script setup lang="ts">
//#region Imports
import { ref, reactive, h, onMounted } from 'vue';
import { MessagePlugin } from 'tdesign-vue-next';
import moment from 'moment';
import { drugApi } from '@/api';
//#endregion

//#region Constants
const statusOptions = [
  { label: '未清洗', value: 0 },
  { label: '已清洗', value: 1 },
  { label: '不用清洗', value: 2 },
];

const dosageFormOptions = [
  { label: '注射液', value: '注射液' },
  { label: '片剂', value: '片剂' },
  { label: '胶囊', value: '胶囊' },
  { label: '颗粒', value: '颗粒' },
];

const drugTypeOptions = [
  { label: '化学药物', value: '化学药物' },
  { label: '生物制品', value: '生物制品' },
  { label: '中药', value: '中药' },
];
//#endregion

//#region State
const formRef = ref();
const editFormRef = ref();
const loading = ref(false);
const tableData = ref<any[]>([]);
const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
  showJumper: true,
});

const formData = reactive({
  drugStandardName: '',
  status: undefined as number | undefined,
});

// 备案号弹窗
const accModalVisible = ref(false);
const accData = ref<any[]>([]);
const accPagination = reactive({ current: 1, pageSize: 5, total: 0 });

// 编辑弹窗
const editModalVisible = ref(false);
const editLoading = ref(false);
const currentEditRecord = ref<any>(null);

const editFormData = reactive<Record<string, any>>({
  cleanedName: '',
  genericNameCn: '',
  genericNameEn: '',
  rdCode: '',
  otherNames: '',
  dosageForm: '',
  drugType: '',
});
//#endregion

//#region Columns Definition
const columns = [
  {
    colKey: 'rowIndex',
    title: '序号',
    width: 60,
    cell: (h: any, { rowIndex }: any) => rowIndex + 1 + (pagination.current - 1) * pagination.pageSize,
  },
  {
    colKey: 'originalName',
    title: '药品名（源数据）',
    width: 180,
    cell: (h: any, { row }: any) => row.drugNickName || row.drugComment || row.drugStandardName || '-',
  },
  {
    colKey: 'genericNameCn',
    title: '商品名(中)',
    width: 150,
    cell: (h: any, { row }: any) => row.drugGoodsNameCn || row.genericNameCn || '-',
  },
  {
    colKey: 'genericNameEn',
    title: '商品名(英)',
    width: 150,
    cell: (h: any, { row }: any) => row.drugGoodsNameEn || row.genericNameEn || '-',
  },
  {
    colKey: 'relatedNo',
    title: '登记号',
    width: 150,
    cell: (h: any, { row }: any) =>
      h(
        't-button',
        {
          theme: 'primary',
          variant: 'text',
          onClick: () => {
            accModalVisible.value = true;
          },
        },
        { default: () => row.acceptanceNo || '-' },
      ),
  },
  {
    colKey: 'companyName',
    title: '公司名',
    width: 150,
    cell: (h: any, { row }: any) => row.companyName || row.companyNameOrigin || '-',
  },
  { colKey: 'dosageForm', title: '剂型', width: 100, cell: (h: any, { row }: any) => row.dosageForm || '-' },
  {
    colKey: 'registerType',
    title: '注册分类',
    width: 120,
    cell: (h: any, { row }: any) => row.registerType || row.registerTypeOrigin || '-',
  },
  {
    colKey: 'drugType',
    title: '药品类型',
    width: 120,
    cell: (h: any, { row }: any) => row.drugType || row.drugTypeOrigin || '-',
  },
  {
    colKey: 'cleanStatus',
    title: '清洗状态',
    width: 120,
    cell: (h: any, { row }: any) => {
      const item = statusOptions.find((opt) => opt.value === row.status || opt.value === row.cleanStatus);
      return item ? item.label : '-';
    },
  },
  { colKey: 'updateUser', title: '操作人', width: 100, cell: (h: any, { row }: any) => row.updateUser || '-' },
  {
    colKey: 'updateTime',
    title: '更新时间',
    width: 170,
    cell: (h: any, { row }: any) => (row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-'),
  },
  {
    colKey: 'operation',
    title: '操作',
    width: 100,
    fixed: 'right' as const,
    cell: (h: any, { row }: any) =>
      h(
        't-button',
        {
          theme: 'primary',
          variant: 'text',
          onClick: () => openEditModal(row),
        },
        { default: () => '编辑' },
      ),
  },
];

const accColumns = [
  { colKey: 'rowIndex', title: '序号', width: 80, cell: (h: any, { rowIndex }: any) => rowIndex + 1 },
  { colKey: 'recordNo', title: '相关登记号/备案号', width: 180 },
  { colKey: 'relatedCompany', title: '相关公司（源数据）', width: 180 },
  { colKey: 'regClassSource', title: '注册分类（源数据）', width: 150 },
  { colKey: 'regClassCleaned', title: '注册分类（清洗后）', width: 150 },
];
//#endregion

//#region Data Fetching
const fetchData = async (curr = pagination.current, size = pagination.pageSize) => {
  loading.value = true;
  try {
    const res = await drugApi.cleanPageData({
      pageNum: curr,
      pageSize: size,
      drugStandardName: formData.drugStandardName || undefined,
      status: formData.status !== undefined ? Number(formData.status) : undefined,
    });
    if (res.code === 0) {
      tableData.value = res.data?.list || [];
      pagination.current = curr;
      pagination.pageSize = size;
      pagination.total = res.data?.total || 0;
    } else {
      MessagePlugin.error(res.msg || '查询失败');
    }
  } catch (e) {
    console.error('Fetch data failed:', e);
  } finally {
    loading.value = false;
  }
};

const onSearch = () => fetchData(1);

const onReset = () => {
  formData.drugStandardName = '';
  formData.status = undefined;
  fetchData(1);
};

const onPageChange = (pageInfo: any) => {
  fetchData(pageInfo.current, pageInfo.pageSize);
};
//#endregion

//#region Edit Modal
const openEditModal = (record: any) => {
  currentEditRecord.value = record;
  editFormData.cleanedName = record.drugStandardName || record.cleanedName || '';
  editFormData.genericNameCn = record.drugNormalNameCn || record.genericNameCn || '';
  editFormData.genericNameEn = record.drugNormalNameEn || record.genericNameEn || '';
  editFormData.rdCode = record.drugCode || record.rdCode || '';
  editFormData.otherNames = record.otherComment || record.otherNames || '';
  editFormData.dosageForm = record.dosageForm || '';
  editFormData.drugType = record.drugType || '';
  editModalVisible.value = true;
};

const submitEdit = async () => {
  editLoading.value = true;
  try {
    if (currentEditRecord.value) {
      const submitData = {
        ...currentEditRecord.value,
        drugStandardName: editFormData.cleanedName,
        drugNormalNameCn: editFormData.genericNameCn,
        drugNormalNameEn: editFormData.genericNameEn,
        drugCode: editFormData.rdCode,
        otherComment: editFormData.otherNames,
        dosageForm: editFormData.dosageForm,
        drugType: editFormData.drugType,
      };
      await drugApi.saveRelation(submitData);
      MessagePlugin.success('保存成功');
      editModalVisible.value = false;
      fetchData();
    }
  } catch (e) {
    console.error(e);
  } finally {
    editLoading.value = false;
  }
};

const onEditModalClose = () => {
  editModalVisible.value = false;
  currentEditRecord.value = null;
};
//#endregion

//#region Acc Modal
const onAccModalClose = () => {
  accModalVisible.value = false;
};
//#endregion

//#region Lifecycle
onMounted(() => {
  fetchData();
});
//#endregion
</script>

// src/pages/Drug/Clean.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Select, Dialog, Form, Input, Tag, Card } from 'tdesign-react';
import moment from 'moment';
import { drugApi } from '../../api/drug';

const { FormItem } = Form;
const { Option } = Select;

const DrugClean: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [tableData, setTableData] = useState<any[]>([]);
  const [pagination, setPagination] = useState({ current: 1, pageSize: 10, total: 0 });

  const [relatedDialogVisible, setRelatedDialogVisible] = useState(false);
  const [editDialogVisible, setEditDialogVisible] = useState(false);
  const [currentEditRecord, setCurrentEditRecord] = useState<any>(null);

  const [filterForm] = Form.useForm();
  const [editForm] = Form.useForm();
  const isFirstRender = useRef(true);

  const handleEdit = (record: any) => {
    setCurrentEditRecord(record);
    editForm.setFieldsValue({
      cleanedName: record.drugStandardName || record.cleanedName,
      genericNameCn: record.drugNormalNameCn || record.genericNameCn,
      genericNameEn: record.drugNormalNameEn || record.genericNameEn,
      rdCode: record.drugCode || record.rdCode,
      otherNames: record.otherComment || record.otherNames,
      dosageForm: record.dosageForm,
      drugType: record.drugType,
    });
    setEditDialogVisible(true);
  };

  const columns = [
    { colKey: 'index', title: '序号', width: 80, cell: ({ rowIndex }: { rowIndex: number }) => rowIndex + 1 },
    {
      colKey: 'originalName',
      title: '药品名（源数据）',
      width: 180,
      cell: ({ row }: any) => row.drugNickName || row.drugComment || row.originalName,
    },
    {
      colKey: 'relatedNo',
      title: '相关受理号/登记号',
      width: 150,
      cell: ({ row }: { row: any }) => (
        <Button variant="text" theme="primary" onClick={() => setRelatedDialogVisible(true)}>
          {row.acceptanceNo || row.relatedNo}
        </Button>
      ),
    },
    {
      colKey: 'cleanStatus',
      title: '清洗状态',
      width: 120,
      cell: ({ row }: { row: any }) => {
        let theme = 'default';
        let statusText = row.cleanStatus;
        if (row.cleanStatus === 0) statusText = '未清洗';
        if (row.cleanStatus === 1) statusText = '已清洗';
        if (row.cleanStatus === 2) statusText = '不用清洗';

        if (statusText === '未清洗') theme = 'warning';
        return (
          <Tag theme={theme as any} variant="light">
            {statusText}
          </Tag>
        );
      },
    },
    {
      colKey: 'cleanedName',
      title: '药品名（清洗后）',
      width: 180,
      cell: ({ row }: any) => row.drugStandardName || row.cleanedName,
    },
    {
      colKey: 'genericNameCn',
      title: '通用名（中文）',
      width: 150,
      cell: ({ row }: any) => row.drugNormalNameCn || row.genericNameCn,
    },
    {
      colKey: 'genericNameEn',
      title: '通用名（英文）',
      width: 150,
      cell: ({ row }: any) => row.drugNormalNameEn || row.genericNameEn,
    },
    { colKey: 'rdCode', title: '研发代号', width: 120, cell: ({ row }: any) => row.drugCode || row.rdCode },
    {
      colKey: 'otherNames',
      title: '其他名（例如结构描述）',
      width: 180,
      cell: ({ row }: any) => row.otherComment || row.otherNames,
    },
    { colKey: 'dosageForm', title: '剂型', width: 100 },
    { colKey: 'drugType', title: '药品类型', width: 120 },
    {
      colKey: 'operation',
      title: '操作',
      width: 100,
      fixed: 'right' as const,
      cell: ({ row }: { row: any }) => (
        <Button theme="primary" variant="text" onClick={() => handleEdit(row)}>
          编辑
        </Button>
      ),
    },
    { colKey: 'operator', title: '操作人', width: 100, cell: ({ row }: any) => row.updateUser || row.operator },
    {
      colKey: 'updateTime',
      title: '更新时间',
      width: 170,
      cell: ({ row }: any) => (row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-'),
    },
  ];

  const fetchData = async () => {
    setLoading(true);
    try {
      const formValues = filterForm.getFieldsValue(true);
      const res = await drugApi.cleanPageData({
        pageNum: pagination.current,
        pageSize: pagination.pageSize,
        drugStandardName: formValues.cleanedName,
        status: formValues.status !== 'all' ? Number(formValues.status) : undefined,
        // ... map other form values if needed
      });
      if (res.code === 0) {
        setTableData(res.data.list);
        setPagination((prev) => ({ ...prev, total: res.data.total }));
      }
    } catch (error) {
      console.error('Fetch data failed:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      fetchData();
      return;
    }
    fetchData();
  }, [pagination.current, pagination.pageSize]);

  const handleSearch = () => {
    if (pagination.current === 1) {
      fetchData();
    } else {
      setPagination((prev) => ({ ...prev, current: 1 }));
    }
  };

  const relatedColumns = [
    { colKey: 'index', title: '序号', width: 80, cell: ({ rowIndex }: { rowIndex: number }) => rowIndex + 1 },
    { colKey: 'recordNo', title: '相关登记号/备案号', width: 180 },
    { colKey: 'relatedCompany', title: '相关公司（源数据）', width: 180 },
    { colKey: 'regClassSource', title: '注册分类（源数据）', width: 150 },
    { colKey: 'regClassCleaned', title: '注册分类（清洗后）', width: 150 },
  ];

  const relatedData = [
    { id: 1, recordNo: '2020GH3914', relatedCompany: '', regClassSource: '', regClassCleaned: '' },
    { id: 2, recordNo: 'JXHL1100068', relatedCompany: '', regClassSource: '', regClassCleaned: '' },
    { id: 3, recordNo: 'CTR20132950', relatedCompany: '', regClassSource: '', regClassCleaned: '' },
  ];

  return (
    <Card bordered={false} style={{ padding: '10px' }}>
      <div style={{ marginBottom: 10 }}>
        <h2 style={{ margin: '0 0 16px 0', fontSize: '18px', fontWeight: 600, color: 'var(--td-text-color-primary)' }}>
          药品名清洗
        </h2>
        <div
          style={{
            background: '#f8fafc',
            padding: '16px',
            borderRadius: '12px',
            border: '1px solid var(--td-border-level-1-color)',
          }}
        >
          <Form
            form={filterForm}
            layout="inline"
            labelWidth={140}
            style={{ display: 'flex', gap: '16px 0', flexWrap: 'wrap' }}
          >
            <FormItem label="药品名（清洗后）" name="cleanedName" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入关键字" clearable style={{ width: 220 }} />
            </FormItem>
            <FormItem label="公司名（清洗后）" name="cleanedCompany" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入关键字" clearable style={{ width: 220 }} />
            </FormItem>
            <FormItem label="母公司" name="parentCompany" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入关键字" clearable style={{ width: 220 }} />
            </FormItem>
            <FormItem label="清洗状态" name="status" initialData="all" style={{ marginBottom: 0 }}>
              <Select style={{ width: 220 }}>
                <Option key="all" value="0" label="未清洗" />
                <Option key="auto" value="1" label="已清洗" />
                <Option key="unmatched" value="2" label="不用清洗" />
              </Select>
            </FormItem>
            <div style={{ display: 'flex', alignItems: 'center', marginLeft: 'auto' }}>
              <Button
                theme="default"
                onClick={() => {
                  filterForm.reset();
                  fetchData();
                }}
                style={{ background: '#fff', marginRight: 8 }}
              >
                重置条件
              </Button>
              <Button theme="primary" onClick={handleSearch}>
                立即查询
              </Button>
            </div>
          </Form>
        </div>
      </div>

      <Table
        data={tableData}
        columns={columns}
        rowKey="id"
        loading={loading}
        bordered
        stripe
        tableLayout="auto"
        hover
        pagination={{
          current: pagination.current,
          pageSize: pagination.pageSize,
          total: pagination.total,
          onChange: (pageInfo) => {
            setPagination((prev) => ({
              ...prev,
              current: pageInfo.current,
              pageSize: pageInfo.pageSize,
            }));
          },
        }}
      />

      {/* 相关备案/登记号 Modal */}
      <Dialog
        header="相关备案/登记号"
        visible={relatedDialogVisible}
        onClose={() => setRelatedDialogVisible(false)}
        footer={null}
        width={800}
      >
        <Table
          data={relatedData}
          columns={relatedColumns}
          rowKey="id"
          bordered
          pagination={{
            current: 2,
            pageSize: 5,
            total: 25,
            showPageSize: false,
            showJumper: false,
          }}
        />
      </Dialog>

      {/* 编辑 Modal */}
      <Dialog
        header="编辑"
        visible={editDialogVisible}
        onClose={() => setEditDialogVisible(false)}
        onConfirm={() => {
          editForm.submit();
        }}
        width={600}
      >
        <div style={{ backgroundColor: '#f3f4f6', padding: 16, marginBottom: 16, borderRadius: 4 }}>
          <p style={{ margin: '0 0 8px 0' }}>
            <strong>药品名（源数据）：</strong> {currentEditRecord?.originalName}
          </p>
          <p style={{ margin: 0 }}>
            <strong>药品类型：</strong> {currentEditRecord?.drugType || '化学药物'}
          </p>
        </div>
        <Form
          form={editForm}
          labelWidth={180}
          onSubmit={(e) => {
            console.log(e);
            setEditDialogVisible(false);
          }}
        >
          <FormItem label="药品名（清洗后）" name="cleanedName">
            <Input />
          </FormItem>
          <FormItem label="通用名（中文）" name="genericNameCn">
            <Input />
          </FormItem>
          <FormItem label="通用名（英文）" name="genericNameEn">
            <Input />
          </FormItem>
          <FormItem label="研发代号" name="rdCode">
            <Input />
          </FormItem>
          <FormItem label="其他名（例如结构名称）" name="otherNames">
            <Input />
          </FormItem>
          <FormItem label="剂型" name="dosageForm">
            <Select>
              <Option key="inj" value="注射液" label="注射液" />
              <Option key="tab" value="片剂" label="片剂" />
            </Select>
          </FormItem>
          <FormItem label="药品类型" name="drugType">
            <Select>
              <Option key="chem" value="化学药物" label="化学药物" />
              <Option key="bio" value="生物制品" label="生物制品" />
            </Select>
          </FormItem>
        </Form>
      </Dialog>
    </Card>
  );
};

export default DrugClean;
