// src/pages/Indication/Database.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Table, Button, Input, Card, Form, Select, Dialog, MessagePlugin } from 'tdesign-react';
import moment from 'moment';
import { indicationApi } from '../../api';
import type { IndicationDictDto, IndicationDictParam, IndicationCategory } from '../../api/types/indication';

const { FormItem } = Form;
const { Option } = Select;

const IndicationDatabase: React.FC = () => {
  const [filterForm] = Form.useForm();
  const isFirstRender = useRef(true);
  
  // Table state
  const [data, setData] = useState<IndicationDictDto[]>([]);
  const [loading, setLoading] = useState(false);
  const [pagination, setPagination] = useState({ current: 1, pageSize: 10, total: 0 });

  // 适应症归类选项
  const [categoryOptions, setCategoryOptions] = useState<IndicationCategory[]>([]);

  useEffect(() => {
    if (!isFirstRender.current) return;
    isFirstRender.current = false;

    // 页面加载时获取下拉分类
    indicationApi.categoryPageData({ pageNum: 1, pageSize: 1000 }).then(res => {
      if (res.code === 0) {
        setCategoryOptions(res.data?.list || []);
      }
    });
    fetchData();
  }, []);

  const fetchData = async (curr = pagination.current, size = pagination.pageSize) => {
    setLoading(true);
    try {
      const values = filterForm.getFieldsValue(true);
      const params: IndicationDictParam = {
        pageNum: curr,
        pageSize: size,
        indicationCategoryId: values.indicationCategoryId,
        indicationStandard: values.indicationStandard,
      };
      
      const res = await indicationApi.dictPageData(params);
      if (res.code === 0) {
        setData(res.data?.list || []);
        setPagination({ current: curr, pageSize: size, total: res.data?.total || 0 });
      } else {
        MessagePlugin.error(res.msg || '查询失败');
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const onSearch = () => fetchData(1);
  const onReset = () => {
    filterForm.reset();
    fetchData(1);
  };

  // ----- 别名（源数据） Modal -----
  const [aliasModalVisible, setAliasModalVisible] = useState(false);
  const [aliasData, setAliasData] = useState<{ aliasName: string }[]>([]);
  const [aliasLoading, setAliasLoading] = useState(false);
  const [aliasPagination, setAliasPagination] = useState({ current: 1, pageSize: 5, total: 0 });
  const [currentTagId, setCurrentTagId] = useState<number>();

  const fetchAliasList = async (tagId: number, curr = 1, size = 5) => {
    setAliasLoading(true);
    try {
      const res = await indicationApi.getIndicationCommentList({ id: tagId, pageNum: curr, pageSize: size });
      if (res.code === 0) {
        const mappedList = (res.data?.list || []).map((name) => ({ aliasName: name }));
        setAliasData(mappedList);
        setAliasPagination({ current: curr, pageSize: size, total: res.data?.total || 0 });
      }
    } catch (e) {
      console.error(e);
    } finally {
      setAliasLoading(false);
    }
  };

  const openAliasModal = (record: IndicationDictDto) => {
    if (!record.indicationTagId) return;
    setCurrentTagId(record.indicationTagId);
    fetchAliasList(record.indicationTagId, 1, 5);
    setAliasModalVisible(true);
  };

  const aliasColumns = [
    { colKey: 'rowIndex', title: '序号', width: 80, cell: ({ rowIndex }: any) => rowIndex + 1 + (aliasPagination.current - 1) * aliasPagination.pageSize },
    { colKey: 'aliasName', title: '源数据适应症（别名）' },
  ];

  const columns = [
    { colKey: 'rowIndex', title: '序号', width: 80, cell: ({ rowIndex }: any) => rowIndex + 1 + (pagination.current - 1) * pagination.pageSize },
    { colKey: 'indicationCategoryName', title: '适应症归类', width: 200 },
    { colKey: 'indicationStandard', title: '适应症', width: 200 },
    {
      colKey: 'statisticCount',
      title: '源数据适应症（别名）',
      width: 180,
      align: 'center' as const,
      cell: ({ row }: any) => (
        <span style={{ color: '#0052d9', cursor: 'pointer', textDecoration: 'underline' }} onClick={() => openAliasModal(row)}>
          {row.statisticCount || 0}
        </span>
      ),
    },
    {
      colKey: 'operation',
      title: '修正编辑',
      width: 100,
      cell: () => (
        <Button theme="primary" variant="text">
          编辑
        </Button>
      ),
    },
    { colKey: 'updateUser', title: '操作人', width: 120 },
    {
      colKey: 'updateTime',
      title: '操作时间',
      width: 170,
      cell: ({ row }: any) => (row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-'),
    },
  ];

  return (
    <Card bordered={false} style={{ padding: '10px' }}>
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ margin: '0 0 16px 0', fontSize: '18px', fontWeight: 600, color: 'var(--td-text-color-primary)' }}>适应症库管理</h2>
        <div style={{ 
          background: '#f8fafc', 
          padding: '16px', 
          borderRadius: '12px',
          border: '1px solid var(--td-border-level-1-color)'
        }}>
          <Form form={filterForm} layout="inline" labelWidth={100} style={{ display: 'flex', gap: '16px 0', flexWrap: 'wrap' }}>
            <FormItem label="适应症归类" name="indicationCategoryId" style={{ marginBottom: 0 }}>
              <Select placeholder="请选择" clearable style={{ width: 220 }}>
                {categoryOptions.map(cat => (
                  <Option key={cat.id} value={cat.id?.toString() || ''} label={cat.categoryName || ''} />
                ))}
              </Select>
            </FormItem>
            <FormItem label="适应症" name="indicationStandard" style={{ marginBottom: 0 }}>
              <Input placeholder="请输入关键字" clearable style={{ width: 220 }} />
            </FormItem>
            <div style={{ display: 'flex', alignItems: 'center', marginLeft: 'auto' }}>
              <Button theme="default" onClick={onReset} style={{ background: '#fff', marginRight: 8 }}>重置条件</Button>
              <Button theme="primary" onClick={onSearch}>搜索</Button>
            </div>
          </Form>
        </div>
      </div>

      <Table 
        data={data} 
        columns={columns} 
        rowKey="indicationTagId" 
        loading={loading}
        bordered 
        stripe 
        tableLayout="auto" 
        hover
        pagination={{
          current: pagination.current,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showJumper: true,
          onChange: (pageInfo) => fetchData(pageInfo.current, pageInfo.pageSize)
        }}
      />

      {/* 源数据别名 Modal */}
      <Dialog
        header="源数据适应症（别名）"
        visible={aliasModalVisible}
        onClose={() => setAliasModalVisible(false)}
        footer={null}
        width={800}
      >
        <Table
          data={aliasData}
          columns={aliasColumns}
          rowKey="aliasName"
          loading={aliasLoading}
          bordered
          stripe
          pagination={{
            current: aliasPagination.current,
            pageSize: aliasPagination.pageSize,
            total: aliasPagination.total,
            onChange: (pageInfo) => fetchAliasList(currentTagId!, pageInfo.current, pageInfo.pageSize)
          }}
        />
      </Dialog>
    </Card>
  );
};

export default IndicationDatabase;

// src/pages/Indication/Database.vue
<template>
  <!--#region 适应症库管理页面 -->
  <t-card bordered>
    <div style="margin-bottom: 16px;">
      <h2 style="margin: 0 0 16px 0; font-size: 18px; font-weight: 600; color: var(--td-text-color-primary);">
        适应症库管理
      </h2>

      <!--#region 搜索表单 -->
      <div style="background: #f8fafc; padding: 16px; border-radius: 12px; border: 1px solid var(--td-border-level-1-color);">
        <t-form
          ref="formRef"
          :data="formData"
          layout="inline"
          label-width="100"
          style="display: flex; gap: 16px 0; flex-wrap: wrap;"
          @submit="onSearch"
        >
          <t-form-item label="适应症归类" name="indicationCategoryId" style="margin-bottom: 0;">
            <t-select
              v-model="formData.indicationCategoryId"
              :options="categoryOptions"
              placeholder="请选择"
              clearable
              style="width: 220px;"
              value-key="id"
              :keys="{ label: 'categoryName', value: 'id' }"
            />
          </t-form-item>
          <t-form-item label="适应症(标准)" name="indicationStandard" style="margin-bottom: 0;">
            <t-input v-model="formData.indicationStandard" placeholder="请输入关键字" clearable style="width: 220px;" />
          </t-form-item>
          <div style="display: flex; align-items: center; margin-left: auto;">
            <t-button theme="default" @click="onReset" style="background: #fff; margin-right: 8px;">
              重置条件
            </t-button>
            <t-button theme="primary" type="submit">
              搜索
            </t-button>
          </div>
        </t-form>
      </div>
      <!--#endregion-->
    </div>

    <!--#region 数据表格 -->
    <t-table
      :data="tableData"
      :columns="columns"
      row-key="indicationTagId"
      :loading="loading"
      bordered
      stripe
      table-layout="auto"
      hover
      :pagination="pagination"
      @page-change="onPageChange"
    />
    <!--#endregion-->

    <!--#region 源数据适应症(别名)弹窗 -->
    <t-dialog
      v-model:visible="aliasModalVisible"
      header="源数据适应症（别名）"
      :footer="false"
      width="800px"
      @close="onAliasModalClose"
    >
      <t-table
        :data="aliasData"
        :columns="aliasColumns"
        row-key="aliasName"
        :loading="aliasLoading"
        bordered
        stripe
        :pagination="aliasPagination"
        @page-change="onAliasPageChange"
      />
    </t-dialog>
    <!--#endregion-->
  </t-card>
  <!--#endregion-->
</template>

<script setup lang="ts">
//#region Imports
import { ref, reactive, h, onMounted } from 'vue';
import { MessagePlugin } from 'tdesign-vue-next';
import moment from 'moment';
import { indicationApi } from '@/api';
import type { IndicationDictDto, IndicationCategory } from '@/api/types/indication';
//#endregion

//#region State
const formRef = ref();
const loading = ref(false);
const tableData = ref<IndicationDictDto[]>([]);
const pagination = reactive({
  current: 1,
  pageSize: 10,
  total: 0,
  showJumper: true,
});

const formData = reactive({
  indicationCategoryId: undefined as number | undefined,
  indicationStandard: '',
});

// 适应症归类选项
const categoryOptions = ref<IndicationCategory[]>([]);

// 别名弹窗
const aliasModalVisible = ref(false);
const aliasData = ref<{ aliasName: string }[]>([]);
const aliasLoading = ref(false);
const aliasPagination = reactive({ current: 1, pageSize: 5, total: 0 });
const currentTagId = ref<number>();
//#endregion

//#region Columns Definition
const columns = [
  {
    colKey: 'rowIndex',
    title: '序号',
    width: 80,
    cell: (h: any, { rowIndex }: any) => rowIndex + 1 + (pagination.current - 1) * pagination.pageSize,
  },
  {
    colKey: 'indicationIcdName',
    title: '适应症(ICD)',
    width: 200,
    cell: (h: any, { row }: any) => row.indicationIcdName || '-',
  },
  { colKey: 'indicationStandard', title: '适应症(标准)', width: 200 },
  {
    colKey: 'indicationCategoryName',
    title: '分类',
    width: 150,
    cell: (h: any, { row }: any) => row.indicationCategoryName || '-',
  },
  {
    colKey: 'statisticCount',
    title: '统计',
    width: 100,
    align: 'center' as const,
    cell: (h: any, { row }: any) =>
      h(
        'span',
        {
          style: { color: '#0052d9', cursor: 'pointer', textDecoration: 'underline' },
          onClick: () => openAliasModal(row),
        },
        row.statisticCount || 0,
      ),
  },
  {
    colKey: 'updateTime',
    title: '更新时间',
    width: 170,
    cell: (h: any, { row }: any) =>
      row.updateTime ? moment(row.updateTime).format('YYYY-MM-DD HH:mm:ss') : '-',
  },
  { colKey: 'updateUser', title: '操作人', width: 120, cell: (h: any, { row }: any) => row.updateUser || '-' },
  {
    colKey: 'operation',
    title: '操作',
    width: 100,
    fixed: 'right' as const,
    cell: (h: any, { row }: any) =>
      h(
        't-button',
        {
          theme: 'primary',
          variant: 'text',
          onClick: () => openEditModal(row),
        },
        { default: () => '编辑' },
      ),
  },
];

const aliasColumns = [
  {
    colKey: 'rowIndex',
    title: '序号',
    width: 80,
    cell: (h: any, { rowIndex }: any) => rowIndex + 1 + (aliasPagination.current - 1) * aliasPagination.pageSize,
  },
  { colKey: 'aliasName', title: '源数据适应症（别名）' },
];
//#endregion

//#region Data Fetching
const fetchData = async (curr = pagination.current, size = pagination.pageSize) => {
  loading.value = true;
  try {
    const params: Record<string, any> = {
      pageNum: curr,
      pageSize: size,
      indicationCategoryId: formData.indicationCategoryId,
      indicationStandard: formData.indicationStandard || undefined,
    };
    const res = await indicationApi.dictPageData(params);
    if (res.code === 0) {
      tableData.value = res.data?.list || [];
      pagination.current = curr;
      pagination.pageSize = size;
      pagination.total = res.data?.total || 0;
    } else {
      MessagePlugin.error(res.msg || '查询失败');
    }
  } catch (e) {
    console.error(e);
  } finally {
    loading.value = false;
  }
};

const onSearch = () => fetchData(1);

const onReset = () => {
  formData.indicationCategoryId = undefined;
  formData.indicationStandard = '';
  fetchData(1);
};

const onPageChange = (pageInfo: any) => {
  fetchData(pageInfo.current, pageInfo.pageSize);
};
//#endregion

//#region Alias Modal
const fetchAliasList = async (tagId: number, curr = 1, size = 5) => {
  aliasLoading.value = true;
  try {
    const res = await indicationApi.getIndicationCommentList({ id: tagId, pageNum: curr, pageSize: size });
    if (res.code === 0) {
      const mappedList = (res.data?.list || []).map((name: string) => ({ aliasName: name }));
      aliasData.value = mappedList;
      aliasPagination.current = curr;
      aliasPagination.pageSize = size;
      aliasPagination.total = res.data?.total || 0;
    }
  } catch (e) {
    console.error(e);
  } finally {
    aliasLoading.value = false;
  }
};

const openAliasModal = (record: IndicationDictDto) => {
  if (!record.indicationTagId) return;
  currentTagId.value = record.indicationTagId;
  fetchAliasList(record.indicationTagId, 1, 5);
  aliasModalVisible.value = true;
};

const onAliasPageChange = (pageInfo: any) => {
  if (currentTagId.value) {
    fetchAliasList(currentTagId.value, pageInfo.current, pageInfo.pageSize);
  }
};

const onAliasModalClose = () => {
  aliasModalVisible.value = false;
};
//#endregion

//#region Edit Modal (placeholder - not implemented in React version either)
const editModalVisible = ref(false);
const openEditModal = (record: IndicationDictDto) => {
  // 编辑功能待实现，同React版本一致
  MessagePlugin.info('编辑功能开发中');
};
//#endregion

//#region Lifecycle
onMounted(async () => {
  // 获取分类下拉选项
  try {
    const res = await indicationApi.categoryPageData({ pageNum: 1, pageSize: 1000 });
    if (res.code === 0) {
      categoryOptions.value = res.data?.list || [];
    }
  } catch (e) {
    console.error(e);
  }
  fetchData();
});
//#endregion
</script>
